# Default
easyframe:
  env: default
  server-name: easyframe-default

# [dev] Environment:
---
spring:
  profiles: dev
easyframe:
  env: dev
  server-name: easyframe-dev

# [test] Environment
---
spring:
  profiles: test
easyframe:
  env: test
  server-name: easyframe-test
logging:
  level:
  org.springframework.cloud.commons.util.InetUtils: TRACE

# [staging] Environment
---
spring:
  profiles: staging
easyframe:
  env: staging
  server-name: easyframe-staging

# [prod] Environment
---
spring:
  profiles: prod
easyframe:
  env: prod
  server-name: easyframe-prod
